### ISSUE TITLE
crash after rotate while tone is playing

### ISSUE THREAD

**Issue by wimh** [Anypodetos/qonvert#2]
I am using Qonvert v1.4.0 from fdroid and I have noticed a small bug.

* In the main screen, I press the musical note
* a popup is opened and a tone starts playing
* now I rotate my device, the application automatically rotates too
* the popup is now closed, but the sound continues
* when the sound stops, the application crashes

Something similar happens when I play a sound from the "Musical intervals" page, it does not always fully crash, sometimes it just exits to the main screen.

**Comment by Anypodetos** [comment]
Thanks for using Qonvert, and good catch! I hope to have that fixed in the next version. Please be patient, though, my time is a bit scarce at the moment.

**Comment by Anypodetos** [comment]
Should be fixed now (version 1.4.1).
